import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  BarChart3,
  Brain,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleDot,
  Clock,
  Code2,
  Copy,
  Download,
  File,
  FilePlus,
  FileText,
  Folder,
  Image,
  Info,
  Layout,
  Lightbulb,
  List,
  Loader2,
  Maximize2,
  MessageCircle,
  MessageSquare,
  Minus,
  Moon,
  PanelLeft,
  PanelRight,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Server,
  Settings,
  Sun,
  Trash2,
  Upload,
  X,
  XCircle,
  Zap
} from 'lucide-react'
import type { FC, SVGProps } from 'react'

type LucideIconComponent = FC<SVGProps<SVGSVGElement>>

/**
 * Lucide 图标 kebab-case name → Component 映射表。
 * 每新增一个图标，只需在此对象中添加一行，TypeScript 会自动推导 IconName 类型。
 */
export const iconMap: Record<string, LucideIconComponent> = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'bar-chart-3': BarChart3,
  brain: Brain,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  circle: Circle,
  'circle-dot': CircleDot,
  clock: Clock,
  'code-2': Code2,
  copy: Copy,
  download: Download,
  file: File,
  'file-plus': FilePlus,
  'file-text': FileText,
  folder: Folder,
  image: Image,
  info: Info,
  layout: Layout,
  lightbulb: Lightbulb,
  list: List,
  'loader-2': Loader2,
  'maximize-2': Maximize2,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  minus: Minus,
  moon: Moon,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  pencil: Pencil,
  plus: Plus,
  'refresh-cw': RefreshCw,
  search: Search,
  server: Server,
  settings: Settings,
  sun: Sun,
  'trash-2': Trash2,
  upload: Upload,
  x: X,
  'x-circle': XCircle,
  zap: Zap
} as const

export type LucideIconName = keyof typeof iconMap
